# Generated by Django 2.2.6 on 2019-11-16 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=128)),
                ('recruiterName', models.CharField(max_length=64)),
                ('designation', models.CharField(max_length=32)),
                ('industry', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=32)),
                ('functionalArea', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=32)),
                ('accountType', models.CharField(max_length=32)),
                ('mobileNumber', models.IntegerField()),
                ('landLine', models.IntegerField()),
                ('website', models.URLField()),
                ('about', models.TextField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
