# Generated by Django 2.2.6 on 2019-11-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdata',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
