# Generated by Django 3.0 on 2019-12-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressdata',
            old_name='type',
            new_name='address_type',
        ),
    ]
