# Generated by Django 2.2.6 on 2019-11-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='landLine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='mobileNumber',
            field=models.IntegerField(null=True),
        ),
    ]
